global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'cliniq_backend'
    static_configs:
      - targets: ['cliniq_backend:8000']
    metrics_path: '/metrics'

  - job_name: 'cliniq_qdrant'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cliniq_qdrant:6333']

  - job_name: 'cliniq_cadvisor'
    static_configs:
      - targets: ['cliniq_cadvisor:8080']